<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.columnizer.js"></script>
<script type="text/javascript" src="theme/js/lib/slick.js"></script>
<script type="text/javascript" src="theme/js/lib/select2.full.js"></script>
<script type="text/javascript" src="theme/js/js.js"></script>