<?php

/**
 * @file
 * OCT Sponsorhips Opportunities
 */

function oct_store_sponsorships_fnl_store_products() {
  return array(
    'product_sponsorships' => array(
      'title' => t('Sponsorship Opportunities'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function oct_store_sponsorships_theme() {

  $return = array();

  $return['oct_store_sponsorships_form'] = array(
    'render element' => 'form',
    'path' => drupal_get_path('module', 'oct_store_sponsorships') . "/templates",
    'template' => 'oct-store-sponsorships-form'
  );

  return $return;
}

function oct_store_sponsorships_form($form, &$form_state, $node) {
  module_load_include('inc','fnl_store', 'includes/fnl_store.checkout');
  $form_state['node'] = $node;

  $form['amount'] = array(
    '#type' => 'textfield',
    '#title' => t('Please send me an invoice for:'),
    '#required' => TRUE,
  );

  $form['first_name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('First Name'),
  );

  $form['last_name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Last Name'),
  );

  $form['company_name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Company Name (as you would like it to appear in publications)'),
  );

  $form['address'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Address'),
  );

  $form['city'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('City'),
  );

  $form['state'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#title' => t('State'),
    '#default_value' => 'OK',
    '#options' => fnl_store_usa_states_options(),
  );

  $form['zip'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Zip'),
    '#maxlength' => 5,
  );

  $form['phone'] = array(
    '#type' => 'masked_input',
    '#mask' => '(999)999-9999',
    '#required' => TRUE,
    '#title' => t('Phone'),
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Email'),
    '#element_validate' => array('fnl_store_element_validate_email'),
  );

  $form['contribute'] = array(
    '#type' => 'textfield',
    '#title' => t('Regretting I cannot attend, but would like to contribute:'),
    '#required' => FALSE,
  );

  $form['packages'] = array(
    '#type' => 'radios',
    '#required' => FALSE,
    '#title' => t(''),
    '#options' => array(
      '0' => '$5,000 Fairy Godmother',
      '1' => '$3,500 King & Queen'
    ),
  );




  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Check Out'),
  );

  return $form;
}

/**
 * Implements hook_preprocess_node().
 */
function oct_store_sponsorships_preprocess_node(&$vars) {
  if($vars['type'] == 'sponsorship_opportunities') {
//    dsm($vars);
    $vars['content']['form'] = drupal_get_form('oct_store_sponsorships_form', $vars['node']);
  }
}