<footer id="site-footer" class="site-footer">
  <div class="site-container">
    <div class="logo">
      <a href="#">
        <img src="theme/images/logo-footer.png" alt="">
        <img class="mobile" src="theme/images/logo-footer-a.png" alt="">
      </a>
    </div>

    <div class="items">

        <p>2501 North Blackwelder, <br/>

          Oklahoma City, OK 73106</p>


        <p>Main Office (Mon–Fri 9–5): 405-606-7003 <br/>

          Box Office (Tue–Fri 1–5): 405-951-0011</p>

      <div class="item">
        <ul class="links">
          <li><a href="#">Site Map</a></li>
          <li><a href="#">Log In</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>