<header id="site-header" class="site-header">
  <div class="header-top">
    <div class="logo">
      <a href="#">
        <img src="theme/images/logo.png" alt="">
        <img class="mobile" src="theme/images/logo-a.png" alt="">
      </a>
    </div>
  </div>
  <div class="header-bottom">
    <a class="btn-home" href="/"></a>
    <a class="btn-nav mobile-only" href="#">Menu <span><span></span></span></a>
    <div class="site-container">
      <nav class="nav">
        <ul class="menu">
          <li><a href="#">Home </a></li>
          <li><a href="#">Productions </a></li>
          <li><a href="#"> Classes </a></li>
          <li class="expanded"><a href="#"> Camps </a>
            <ul class="menu">
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Summer</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Fall</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Winter</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Spring Break</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Camp Info</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">FAQs</a></li>
            </ul>
          </li>
          <li class="expanded"><a href="#"> Camps </a>
            <ul class="menu">
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Summer</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Fall</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Winter</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Spring Break</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">Camp Info</a></li>
              <li class="first last leaf"><a href="/content/classes-camps-faqs" title="">FAQs</a></li>
            </ul>
          </li>
          <li><a href="#"> Fairy Tale Ball </a></li>
          <li><a href="#"> Friday Fun Night </a></li>
          <li><a href="#"> About Us</a></li>
        </ul>
      </nav>

      <div id="block-fnl-store-cart-fnl-store-cart" class="block block-fnl-store-cart">


        <div class="content">
          <div class="fnl-store-cart-block">
            <a href="/cart"><span class="text">Cart</span> <span class="count">0</span></a></div>  </div>
      </div>
    </div>
  </div>
</header>