<footer id="site-footer" class="site-footer">
  <div class="inner">
    <div class="logo">
      Oklahoma
      Children's
      Theatre
    </div>

    <div class="contact-info">
      <p>
      2501 North Blackwelder, Oklahoma City, OK 73106
      <span>Main office: 405-606-7003</span> <span>Box Office: 405-951-0011</span>
      </p>
    </div>

    <nav class="footer-nav">
      <ul>
        <li><a href="#">Site Map</a></li>
        <lI><a href="#">Log In</a></lI>
      </ul>
    </nav>
  </div>
</footer>