<header id="site-header" class="site-header">
  <div class="inner">
    <div class="logo">
      <a href="#">
        <img src="theme/images/logo.png">
      </a></div>
    <nav class="nav">
      <ul class="menu">
        <li class="active-trail first leaf"><a href="#">Home</a></li>
        <li class="expanded"><a href="#">About Us</a>
          <ul class="menu">
            <li class="first leaf"><a href="#">Board of Directors</a></li>
            <li class="leaf"><a href="#">Staff</a></li>
            <li class="leaf"><a href="#">Artists</a></li>
            <li class="leaf"><a href="#">History</a></li>
            <li class="leaf"><a href="#">Location</a></li>
            <li class="last leaf"><a href="#">What We Do</a></li>
          </ul>
        </li>
        <li class="expanded"><a href="#">Productions</a>
          <ul class="menu">
            <li class="first leaf"><a href="#">Theatre</a></li>
            <li class="last leaf"><a href="#">Touring</a></li>
          </ul>
        </li>
        <li class="expanded"><a href="#">Classes</a>
          <ul class="menu">
            <li class="first last leaf"><a href="#">FAQs</a></li>
          </ul>
        </li>
        <li class="expanded"><a href="#">Camps</a>
          <ul class="menu">
            <li class="first leaf"><a href="#">Upcoming Camps</a></li>
            <li class="leaf"><a href="#">Camp List</a></li>
            <li class="leaf"><a href="#">Descriptions</a></li>
            <li class="last leaf"><a href="#">FAQs</a></li>
          </ul>
        </li>
        <li class="expanded"><a href="#">Fairy Tale Ball</a>
          <ul class="menu">
            <li class="first leaf"><a href="#">Register Online</a></li>
            <li class="leaf"><a href="#">General Information</a></li>
            <li class="leaf"><a href="#">Sponsorship Opportunities</a></li>
            <li class="last leaf"><a href="#">Auction Items</a></li>
          </ul>
        </li>
        <li class="leaf"><a href="#">Friday Fun Night</a></li>
        <li class="last leaf"><a href="#">Contact Us</a></li>
      </ul>
    </nav>
  </div>
</header>